#!/bin/bash

if [ ! -f "main.db" ]; then
    python activation/createdb.py
fi

if [ -f "activation/bashactivated" ]; then
    source .venv/bin/activate
    python3 main.py
else
    python3 -m pip install -U virtualenv
    virtualenv .venv
    source .venv/bin/activate
    python3 -m pip install -U flask flask-sqlalchemy
    touch activation/bashactivated
    clear
    source .venv/bin/activate
    python3 main.py
fi
