#!/bin/bash

if [ ! -f "activation/bashactivated" ]; then
    python3 -m pip install -U virtualenv
    virtualenv .venv
    source .venv/bin/activate
    python3 -m pip install -U flask flask-sqlalchemy python-dotenv
    touch activation/bashactivated
    clear
fi


if [ ! -f "main.db" ]; then
    source .venv/bin/activate
    python activation/createdb.py
fi


source .venv/bin/activate
flask run
